### ISSUE TITLE
Error in plotHeatmap() function

### ISSUE THREAD

**Issue by nhuhoa** [shahcompbio/schnapps#10]
Hi Marc, 
When I run function: 
p <- plotHeatmap(CNbins=CNbins, clusters=NULL, 
                   plottree=T, plotcol = 'copy')

Error: Error in make_copynumber_heatmap(copynumber, format_clones(as.data.frame(clusters),  : 
  object 'legendname' not found

The reason is in plotHeatmap function, there is no option plotcol='copy', so 'legendname' is not initialized. I suggest to initialize legendname first in the plotHeatmap function, so this function can cover all cases. 

Best, 
Hoa Tran

**Comment by marcjwilliams1** [comment]
Thanks Hoa, added a check now so this error is caught earlier. Thanks.
