### ISSUE TITLE
Error in plotting: plotCNprofileBAF()

### ISSUE THREAD

**Issue by nhuhoa** [shahcompbio/schnapps#13]
Dear Marc, 

In the previous version, I can run plotCNprofileBAF() without any problem. 
But for schnapps_0.1.0, I have just installed this package 2-3 weeks ago, there is a problem 
with this function, here is the error: 
"Error in getBins(binsize = binsize) : object 'hg19_chrlength' not found"
Do you have any idea about this issue? 

Thanks, 

My script: 
CNbins <- ascn$data
CNbins <- CNbins %>% inner_join(clones_labels_df, by = "cell_id")
  CNbins <- CNbins %>%
    group_by(chr, start, end, clone_id) %>%
    summarise(state = schnapps:::Mode(state),
              state_phase = schnapps:::Mode(state_phase),
              state_min = schnapps:::Mode(state_min),
              BAF = median(BAF),
              copy = median(copy,na.rm=T)) %>%
    ungroup() %>%
    mutate(cell_id = paste0("Clone ", clone_id))
  
  plots <- list()
  c <- 0
  for (cl in unique(CNbins$cell_id)){
    cat('###', cl,' \n')
    c <- c + 1
    plots[[c]] <- schnapps::plotCNprofileBAF(CNbins, cellid = cl)
    cat(' \n \n')
  }

**Comment by marcjwilliams1** [comment]
I'm not sure why this would be happening, the most recent CI check on Aug 19th passed (which includes checking this function). What R version are you using?

**Comment by nhuhoa** [comment]
Hi Marc, 
I am use R version 3.6.2, Ubuntu server. 
I guess error is from this function: 
https://rdrr.io/github/shahcompbio/schnapps/man/getBins.html

Thanks,
Hoa

**Comment by nhuhoa** [comment]
Hi Marc, 
I debug the program and see that if I replace plotting most updated function by old version, it works!!! So error come from this function: 
# New version: 
# pl <- CNbins %>%
  #   dplyr::filter(cell_id == cellid) %>%
  #   plottinglist(., xaxis_order = xaxis_order, maxCN = maxCN)
  
  # Using old version, it works!!!
  pl <- CNbins %>%
  dplyr::filter(cell_id == cellid) %>%
  plottinglist(.)

Thanks, 
Hoa Tran

**Comment by marcjwilliams1** [comment]
Thanks Hoa, I will investigate further.
