### ISSUE TITLE
How to get input files

### ISSUE THREAD

**Issue by alhafidzhamdan** [shahcompbio/schnapps#27]
Hi there,
Thanks for creating this wonderful package.
I've read your recent biorxiv paper on HGSOC ("Immune and malignant cell phenotypes of ovarian cancer are determined by distinct mutational processes") - very exciting findings! 
I have a question regarding my own data.

I have a bulk WGS data and a paired scATAC-seq and scRNA-seq data on one tumour sample.
From the bulk WGS data, I used GATK-HaplotypeCaller to generate a germline heterozygous SNPs VCF. 
I have then run cellSNP-lite using the VCF file and the BAM file from scRNA-seq to call germline heterozygous SNPs in the scRNA-seq data, and I'm guessing that the output of this is "haplotypes_rna" in your tutorial.

My question is how do I generate haplotype blocks from this?
And also how do i generate the input for "CNbins" ? I don't have single cell WGS data and I noticed that in that biorxiv paper you didn't have scWGS data either.

Thanks for your time!

A

**Comment by marcjwilliams1** [comment]
Hi @alhafidzhamdan thanks for your interest in the package. Apologies that the documentation is a bit sparse at present, I plan on updating the docs to cover in more detail how to generate the inputs soon. Generating haplotypes and haplotype counts is step 8 here https://single-cell-pipeline.readthedocs.io/en/latest/ 

However, the haplotype blocks are not so important for scRNAseq data (especially if you don't have matched scDNAseq) as the data is so sparse. So it might be worth trying schnapps without haplotype blocks. In this case you could just add a dummy "hap_label" and assign each het SNP a unique integer ID (they should be the same across all cells).

If you have a dataframe (`snpdf`) with `chr`, `position`, `cell_id`, `patient`, `sample`,  `allele0` and `allele1` (where allele1 and allele0 are the counts for the ref and alt then something like this would work:
```r
library(data.table)
haps <- as.data.table(snpdf)[, hap_label := .GRP, by = list(chr, position)]
```

Then you can phase these SNPs as follows.
```r
haplotypes_rna <- format_haplotypes_rna(snpdf)
```

After this you should be able to follow the rest of the vignette (apart from the scWGS bits).

btw I think the same the same approach will likely work with scATACseq. I haven't tried it yet but it's on my to do list.

**Comment by alhafidzhamdan** [comment]
Hi Marc,
Thanks a lot for getting back so quickly. I will try your approach and will up date you with the results. 
I was also wondering how to generate the dataframe CNbins using bulk WGS and scRNA/ATAC seq data?
I realise I need to use HMMcopy somehow but do you have your own guide/tutorial as to how to generate this from a 10x bam file? 

A

**Comment by alhafidzhamdan** [comment]
HI @marcjwilliams1 thanks for getting back. I will try you suggestion and will let you know if it works.
I wonder how to generate the CNbins file. I presume i have to use HMMcopy on my scRNAseq BAM file. 
I found https://single-cell-pipeline.readthedocs.io/en/latest/install.html but i wonder if you had any guide/tutorial as to how to populate the input yaml file for the HMMcopy step ? Or if you have any other suggestions as to how i can use my scRNAseq/scATACseq to generate HMMcopy-like CNbins file.

A

**Comment by marcjwilliams1** [comment]
If you're just analyzing scRNA/scATAC you don't need the CNbins file. All that schnapps can do for scRNA at the moment is identify allelic imbalance at the chromosome arm level. So once you have the `haplotoypes_rna` dataframe as above you can just do the following:

```r
#heatmap of BAF per chromosome clustered using hierarchical clustering
plotHeatmapBAF(haplotypes_rna)

#cluster the per arm values using dirichilet process clustering based on read counts per arm
haplotypes_per_arm <- per_arm_baf_mat(haplotypes_rna)
ascn_rna_dp <- assign_states_dp(haplotypes_per_arm$bafperchr)

#plot the DP clust assignments in a heatmap
plotHeatmap(ascn_rna_dp$hscn, 
            clusters = ascn_rna_dp$clusters,
            reorderclusters = TRUE,
            spacer_cols = 15, 
            plotcol = "BAF", 
            plottree = FALSE,
            widenarm = TRUE, #make sure this is true
            show_legend = FALSE)
```

It would of course be better to incorporate both read depth information (counting reads using HMMcopy or the like) and allele imbalance information into the model and calculate proper allele specific states, this is something I've been thinking about but haven't got round to yet.

**Comment by alhafidzhamdan** [comment]
ok that's great @marcjwilliams1 thanks for your help, I will close this issue for now.

**Comment by kanefos** [comment]
Just following this thread - was signals previously called schnapps?
