### ISSUE TITLE
Save clusters and tree output from plotHeatmap

### ISSUE THREAD

**Issue by nhuhoa** [shahcompbio/schnapps#9]
Hi Marc, 

I would like to have a suggestion. In the plotHeatmap() function, can you add the code to save the output of clustering and tree that generated from cluster output? It will be helpful to the next step. I am not sure whether hdbscan algo is deterministic or contain random initialization step. So the best way is to keep the output of clustering for further analysis also. 

Thanks, 
Best, 
Hoa

**Comment by marcjwilliams1** [comment]
Hi @nhuhoa,

I'd recommend you do the following:
```
clust <- umap_clustering(ascn)
plotHeatmap(ascn, clusters = clust$clustering, tree =clust$tree)
```
Does that work for your purposes?

**Comment by marcjwilliams1** [comment]
Closing this, if this is still an issue, just let me know.
